sources:
  - name: threshold-tbtc-mainnet
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/7cc7a8b42a7f9288f995125f449b432c/subgraphs/id/2E1dYAE5EsJdfC1gyzp98hHPPCxSoX2TSoBivzFto47b
    transforms:
      - autoPagination:
          limitOfRecords: 2000
plugins:
  - pollingLive:
      defaultInterval: 1000
documents:
  - ./src/pages/query.graphql