query GetRitualsQueryByUser($authority: Bytes, $id: ID, $txHash: Bytes, $skip: Int = 0) {
  rituals(
    first: 1000
    skip: $skip
    where: {
      and: [
        {
          or: [
            { authority: $authority }
            { id: $id }
            { transactions_: { transactionHash: $txHash } }
          ]
        }
        { id_not_in: ["1", "2", "3", "4", "5", "6"] }
      ]
    }
    orderBy: id
    orderDirection: asc
  ) {
    id
    authority
    participants
    status
    startedAt
    endedAt
    transcriptCount
    aggregationCount
    publicKey {
      word0
      word1
    }
    transactions(orderBy: timestamp, orderDirection: desc) {
      eventType
      participant
      timestamp
      transactionHash
    }
  }
  ritualCounter(id: "global") {
    total: totalRituals
    unsuccessful: failedRituals
    successful: successfulRituals
    notEnded: pendingRituals
  }
}

query GetRitualsQueryByStakingProvider($id: Bytes!, $skip: Int = 0) {
  rituals(
    first: 1000
    skip: $skip
    where: {
      and: [
        { participants_contains: [$id] }
        { id_not_in: ["1", "2", "3", "4", "5", "6"] }
      ]
    }
    orderBy: id
    orderDirection: asc
  ) {
    id
    authority
    participants
    status
    startedAt
    endedAt
    transcriptCount
    aggregationCount
    publicKey {
      word0
      word1
    }
    transactions(orderBy: timestamp, orderDirection: desc) {
      eventType
      participant
      timestamp
      transactionHash
    }
  }
}

query GetAllRitualsQuery($skip: Int = 0) {
  rituals(
    first: 1000
    skip: $skip
    where: { id_not_in: ["1", "2", "3", "4", "5", "6"] }
    orderBy: id
    orderDirection: asc
  ) {
    id
    authority
    participants
    status
    startedAt
    endedAt
    transcriptCount
    aggregationCount
    publicKey {
      word0
      word1
    }
    transactions(orderBy: timestamp, orderDirection: desc) {
      eventType
      participant
      timestamp
      transactionHash
    }
  }
  ritualCounter(id: "global") {
    total: totalRituals
    unsuccessful: failedRituals
    successful: successfulRituals
    notEnded: pendingRituals
  }
}

query GetAllStakersQuery {
  stakingProviders(first: 1000, orderBy: authorized, orderDirection: desc) {
    id
    operator
    authorized
    deauthorizing
    startTimestamp
  }
}

query SearchStakers($id: ID!, $address: Bytes) {
  stakingProviders(where: { or: [{ id: $id }, { operator: $address }] }) {
    id
    operator
    authorized
    deauthorizing
    startTimestamp
  }
}

query StakerDetail($id: ID!) {
  stakingProvider(id: $id) {
    id
    operator
    authorized
    deauthorizing
    startTimestamp
    authorizationEvents(first: 10, orderBy: timestamp, orderDirection: desc) {
      id
      eventType
      fromAmount
      toAmount
      timestamp
      blockNumber
      transactionHash
    }
  }
}
